"""Regenerate OTLP allocation-preflight metadata from the exact selected pdata.

This intentionally understands pdata's generated decoder shape, not arbitrary Go.
Fail rather than silently emit partial metadata when that shape changes. CI checks
this against the module selected by go.mod; no internal package is imported.
"""
import argparse, hashlib, pathlib, re, subprocess, sys

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--pdata-dir", type=pathlib.Path)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
if args.pdata_dir is None:
    args.pdata_dir = pathlib.Path(subprocess.check_output(
        ["go", "list", "-m", "-mod=readonly", "-f", "{{.Dir}}", "go.opentelemetry.io/collector/pdata"],
        cwd=root, text=True).strip())
base = args.pdata_dir / "internal"
files={}
types={}
for p in base.glob('generated_proto_*.go'):
 s=p.read_text()
 for typ,body in re.findall(r'type (\w+) struct \{(.*?)\n\}',s,re.S):
  fields={m.group(1):m.group(2) for m in re.finditer(r'^\s*(\w+)\s+([\w\[\]*]+)\s*$',body,re.M)}
  types[typ]=fields
  if f'func (orig *{typ}) UnmarshalProto' in s: files[typ]=s
roots=['ExportLogsServiceRequest','ExportTraceServiceRequest','ExportMetricsServiceRequest']
queue=roots.copy(); seen={}
while queue:
 typ=queue.pop(0)
 if typ in seen: continue
 s=files[typ]
 proto=s.split(f'func (orig *{typ}) UnmarshalProto',1)[1].split('\nfunc ',1)[0]
 js=s.split(f'func (orig *{typ}) UnmarshalJSON',1)[1].split('\nfunc ',1)[0]
 pcases=re.findall(r'\n\t\tcase (\d+):\n(.*?)(?=\n\t\t(?:case |default:)|\Z)',proto,re.S)
 jcases=re.findall(r'\n\t\tcase ("[^\n]+):\n(.*?)(?=\n\t\t(?:case |default:)|\Z)',js,re.S)
 assert pcases or not types[typ], (typ, "no protobuf cases extracted")
 seen[typ]=[]
 for num,body in pcases:
  names=set(re.findall(r'for field (\w+)',body)); assert len(names)==1,(typ,num,names)
  name=names.pop()
  ftype=types[typ].get(name) or types.get(typ+'_'+name,{}).get(name)
  assert ftype,(typ,num,name)
  target=ftype.lstrip('[]*')
  ischild=target in files
  ispacked=ftype in ['[]uint64','[]int64','[]uint32','[]int32','[]float64','[]float32']
  if not ischild and not ispacked: continue
  keys=[]
  for k,b in jcases:
   if re.search(r'\.'+name+r'\b',b): keys += re.findall(r'"([^"]+)"',k)
  assert keys,(typ,num,name,'missingjson')
  if ispacked:
   pk='8' if 'WireTypeI64' in body else '4' if 'WireTypeI32' in body else '1'
   target='';
  else:pk='0';queue.append(target)
  seen[typ].append([int(num),name,target,ftype.startswith('[]'),int(pk),keys])

for typ, fields in seen.items():
    method = files[typ].split(f"func (orig *{typ}) UnmarshalProto", 1)[1].split("\nfunc ", 1)[0]
    recursive_calls = method.count(".UnmarshalProto(")
    # Fixed-width ID leaf codecs are not nested messages and have no repeated
    # descendants. Everything else must be represented in the traversal graph.
    id_leaves = sum(method.count("." + name + ".UnmarshalProto(")
                    for name, typ in types[typ].items() if typ in {"TraceID", "SpanID"})
    if recursive_calls != sum(bool(f[2]) for f in fields) + id_leaves:
        raise ValueError((typ, "unaccounted embedded protobuf message", recursive_calls, fields))

# Include every reachable decoder in the fingerprint so schema or generated
# decoder changes require review, even when existing field metadata is unchanged.
fingerprint = hashlib.sha256("".join(files[t] for t in sorted(seen)).encode()).hexdigest()
lines = ["// Code generated by .scripts/generate_otlp_preflight_schema.py; DO NOT EDIT.",
         "// Source: selected OpenTelemetry pdata generated decoders.",
         "// Decoder SHA-256: " + fingerprint, "package otlpwire", "", "type preflightKind uint8", "const (", "pfUnknown preflightKind = iota"]
for t in sorted(seen): lines.append("pf"+t)
lines += [")", "", "var preflightSchemas = [...]preflightSchema{", "pfUnknown: {},"]
items = {"LogRecord", "Span", "NumberDataPoint", "HistogramDataPoint", "ExponentialHistogramDataPoint", "SummaryDataPoint"}
for typ in sorted(seen):
    lines.append("pf%s: {item: %s, fields: []preflightField{" % (typ, str(typ in items).lower()))
    for num,name,target,repeated,packed,keys in sorted(seen[typ]):
        if len(keys)>2: raise ValueError((typ, name, keys))
        keys = keys + [""]*(2-len(keys))
        lines.append('{%d, "%s", "%s", %s, %s, %d},' % (num, keys[0], keys[1], "pf"+target if target else "pfUnknown", str(repeated).lower(), packed))
    lines.append("}},")
lines.append("}")
out = subprocess.check_output(["gofmt"], input="\n".join(lines).encode())
path = root / "library/otlpwire/preflight_schema.go"
if args.check:
    if not path.exists() or path.read_bytes() != out:
        sys.exit("OTLP preflight schema differs from selected pdata; regenerate and review before upgrading")
else:
    path.write_bytes(out)
print("Verified %d reachable OTLP message decoders (%s)" % (len(seen), fingerprint))
